### ISSUE TITLE
imageAndFlowables breaks in place context

### ISSUE THREAD

**Issue by wichert** [zopefoundation/z3c.rml#19]
[place](http://www.reportlab.com/software/rml-reference/#place) can have `imageAndFlowables` as a child. This is a minimal document to try this:

``` xml
<document filename="/dev/null">
   <pageDrawing>
    <place x="285" y="550" width="240" height="135">
      <imageAndFlowables imageName="rml/images/calendar.jpg">
        <para>This is a test</para>
      </imageAndFlowables>
    </place>
  </pageDrawing>
</document>
```

Trying to render that results in this:

```
wichert@kim ~/rml $ bin/rml2pdf x.rml
Traceback (most recent call last):
  File "bin/rml2pdf", line 9, in <module>
    load_entry_point('z3c.rml==2.5.0', 'console_scripts', 'rml2pdf')()
  File "/Users/wichert/rml/lib/python2.7/site-packages/z3c/rml/rml2pdf.py", line 67, in main
    go(*args)
  File "/Users/wichert/rml/lib/python2.7/site-packages/z3c/rml/rml2pdf.py", line 61, in go
    doc.process(outputFile)
  File "/Users/wichert/rml/lib/python2.7/site-packages/z3c/rml/document.py", line 712, in process
    self.processSubDirectives(select=('pageInfo', 'pageDrawing'))
  File "/Users/wichert/rml/lib/python2.7/site-packages/z3c/rml/directive.py", line 120, in processSubDirectives
    directive.process()
  File "/Users/wichert/rml/lib/python2.7/site-packages/z3c/rml/canvas.py", line 996, in process
    super(Drawing, self).process()
  File "/Users/wichert/rml/lib/python2.7/site-packages/z3c/rml/directive.py", line 123, in process
    self.processSubDirectives()
  File "/Users/wichert/rml/lib/python2.7/site-packages/z3c/rml/directive.py", line 120, in processSubDirectives
    directive.process()
  File "/Users/wichert/rml/lib/python2.7/site-packages/z3c/rml/canvas.py", line 415, in process
    flowWidth, flowHeight = flow.wrap(width, height)
  File "/Users/wichert/rml/lib/python2.7/site-packages/reportlab/platypus/flowables.py", line 1174, in wrap
    canv = self.canv
AttributeError: ImageAndFlowables instance has no attribute 'canv'
```

**Comment by strichter** [comment]
Defintely works now.
