### ISSUE TITLE
blockTableStyle not working:

### ISSUE THREAD

**Issue by hero100era** [zopefoundation/z3c.rml#75]
python 3.7.5,  z3c.rml 3.9.1 , flask 1.1.1;

[test.zip](https://github.com/zopefoundation/z3c.rml/files/4368243/test.zip)

The BlockTable with style attribute will cause error：

```
Traceback (most recent call last):
  File "c:\users\adm\venv\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\users\adm\venv\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "c:\users\adm\venv\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\adm\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\adm\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\adm\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\adm\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\adm\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\adm\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\adm\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\adm\Desktop\test.py", line 15, in test
    datau= rml2pdf.go('test-pars.xml', outputFileName=buf)
  File "c:\users\adm\venv\lib\site-packages\z3c\rml\rml2pdf.py", line 73, in go
    doc.process(outputFile)
  File "c:\users\adm\venv\lib\site-packages\z3c\rml\document.py", line 721, in process
    self.doc.multiBuild(self.flowables, maxPasses=maxPasses)
  File "c:\users\adm\venv\lib\site-packages\reportlab\platypus\doctemplate.py", line 1143, in multiBuild
    self.build(tempStory, **buildKwds)
  File "c:\users\adm\venv\lib\site-packages\reportlab\platypus\doctemplate.py", line 1056, in build
    self.handle_flowable(flowables)
  File "c:\users\adm\venv\lib\site-packages\reportlab\platypus\doctemplate.py", line 912, in handle_flowable
    if frame.add(f, canv, trySplit=self.allowSplitting):
  File "c:\users\adm\venv\lib\site-packages\reportlab\platypus\frames.py", line 217, in _add
    flowable.drawOn(canv, self._x + self._leftExtraIndent, y, _sW=aW-w)
  File "c:\users\adm\venv\lib\site-packages\reportlab\platypus\flowables.py", line 114, in drawOn
    self._drawOn(canvas)
  File "c:\users\adm\venv\lib\site-packages\reportlab\platypus\flowables.py", line 95, in _drawOn
    self.draw()#this is the bit you overload
  File "c:\users\adm\venv\lib\site-packages\reportlab\platypus\tables.py", line 1482, in draw
    self._drawLines()
  File "c:\users\adm\venv\lib\site-packages\reportlab\platypus\tables.py", line 1116, in _drawLines
    self.canv.setDash(dash)
  File "c:\users\adm\venv\lib\site-packages\reportlab\pdfgen\canvas.py", line 1740, in setDash
    bad = [_ for _ in array if not isinstance(_,(int,float)) or _ < 0]
TypeError: 'object' object is not iterable
```

**Comment by hero100era** [comment]
> python 3.7.5, z3c.rml 3.9.1 , flask 1.1.1;
> 
> the flask code as followin:
> 
> > test.py
> 
> > `from flask import Flask, render_template, make_response from z3c.rml import rml2pdf import io`

**Comment by samkuehn** [comment]
This appears to be an issue with reportlab==3.5.42 if you do not specify the dash attribute in a lineStyle within blockTableStyle it will break.  An object is passed to setDash here: https://github.com/MrBitBucket/reportlab-mirror/blob/master/src/reportlab/platypus/tables.py#L1116

Below will not work:
```
<blockTableStyle id="style">
  <lineStyle start="0,0" stop="-1,0" kind="linebelow" colorName="black" thickness="0"/>
</blockTableStyle>
```
Below will work (but looks strange).
```
<blockTableStyle id="style">
  <lineStyle start="0,0" stop="-1,0" kind="linebelow" colorName="black" thickness="0" dash="1"/>
</blockTableStyle>
```

Perhaps we just need a sane default for the dash attribute in the lineStyle RML?

**Comment by jugmac00** [comment]
@samkuehn I bet you already know, but just in case, reportlab moved its repo away from bitbucket to https://hg.reportlab.com/hg-public/reportlab/file/tip/

**Comment by samkuehn** [comment]
@ljugmac00 I did realize this, but did not know that you could link to a line in the official repo.  I have updated the link above.

**Comment by samkuehn** [comment]
This seems to be fixed in z3c.rml==3.10.0

**Comment by strichter** [comment]
Example works in z3c.rml 4.1.0 and Reportlan 3.5.56.
