### ISSUE TITLE
<para> tag causing list index out of range error

### ISSUE THREAD

**Issue by jcharlto** [zopefoundation/z3c.rml#93]
Hello,

After using rml2pdf for over a year, a problem with <para> tags popped up in my code when I used it recently. Suddenly, I began getting a list index out of range error. After doing some debugging, I tracked it down to the <para> tag.

Here's the error:
```pycon
In [22]: rml2pdf.go(root_path + r'\Test File.rml', root_path + r'\Output.pdf')
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\reportlab\platypus\paraparser.py", line 3220, in parse
    self.feed(text)
  File "C:\Program Files\Anaconda3\lib\html\parser.py", line 111, in feed
    self.goahead(0)
  File "C:\Program Files\Anaconda3\lib\html\parser.py", line 165, in goahead
    self.handle_data(rawdata[i:j])
  File "C:\Program Files\Anaconda3\lib\site-packages\z3c\rml\paraparser.py", line 244, in handle_data
    reportlab.platypus.paraparser.ParaParser.handle_data(self, data)
  File "C:\Program Files\Anaconda3\lib\site-packages\reportlab\platypus\paraparser.py", line 3122, in handle_data
    frag = copy.copy(self._stack[-1])
IndexError: list index out of range


During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
  File "C:\Users\JCHARL~1\AppData\Local\Temp/ipykernel_74424/1767421038.py", line 1, in <module>
    rml2pdf.go(root_path + r'\Test File.rml', root_path + r'\Output.pdf')
  File "C:\Program Files\Anaconda3\lib\site-packages\z3c\rml\rml2pdf.py", line 75, in go
    doc.process(outputFile)
  File "C:\Program Files\Anaconda3\lib\site-packages\z3c\rml\document.py", line 736, in process
    self.processSubDirectives(select=('template', 'story'))
  File "C:\Program Files\Anaconda3\lib\site-packages\z3c\rml\directive.py", line 121, in processSubDirectives
    directive.process()
  File "C:\Program Files\Anaconda3\lib\site-packages\z3c\rml\template.py", line 46, in process
    self.parent.flowables = super().process()
  File "C:\Program Files\Anaconda3\lib\site-packages\z3c\rml\flowable.py", line 1633, in process
    self.processSubDirectives()
  File "C:\Program Files\Anaconda3\lib\site-packages\z3c\rml\directive.py", line 121, in processSubDirectives
    directive.process()
  File "C:\Program Files\Anaconda3\lib\site-packages\z3c\rml\flowable.py", line 323, in process
    self.parent.flow.append(self.klass(**args))
  File "C:\Program Files\Anaconda3\lib\site-packages\z3c\rml\paraparser.py", line 261, in __init__
    reportlab.platypus.paragraph.cleanBlockQuotedText, manager)
  File "C:\Program Files\Anaconda3\lib\site-packages\z3c\rml\paraparser.py", line 273, in _setup
    style, frags, bulletTextFrags = _parser.parse(text, style)
  File "C:\Program Files\Anaconda3\lib\site-packages\reportlab\platypus\paraparser.py", line 3222, in parse
    annotateException('\nparagraph text %s caused exception' % ascii(text))
  File "C:\Program Files\Anaconda3\lib\site-packages\reportlab\lib\utils.py", line 1297, in annotateException
    rl_reraise(t,t(sep.join((_ for _ in (msg,str(v),postMsg) if _))),b)
  File "C:\Program Files\Anaconda3\lib\site-packages\reportlab\lib\utils.py", line 169, in rl_reraise
    raise v.with_traceback(b)
  File "C:\Program Files\Anaconda3\lib\site-packages\reportlab\platypus\paraparser.py", line 3220, in parse
    self.feed(text)
  File "C:\Program Files\Anaconda3\lib\html\parser.py", line 111, in feed
    self.goahead(0)
  File "C:\Program Files\Anaconda3\lib\html\parser.py", line 165, in goahead
    self.handle_data(rawdata[i:j])
  File "C:\Program Files\Anaconda3\lib\site-packages\z3c\rml\paraparser.py", line 244, in handle_data
    reportlab.platypus.paraparser.ParaParser.handle_data(self, data)
  File "C:\Program Files\Anaconda3\lib\site-packages\reportlab\platypus\paraparser.py", line 3122, in handle_data
    frag = copy.copy(self._stack[-1])
IndexError: 
 paragraph text '<para>Hello World!</title> <para>Foobar</para> </story></para>' caused exception list index out of range
```

Here's my code:
```python
root_path = r'H:\Temp'
import sys; 
sys.path.insert(0, root_path);

import z3c.rml.tests
from z3c.rml import rml2pdf, attr

rml2pdf.go(root_path + r'\Test File.rml', root_path + r'\Output.pdf')
```

I'm using python 3.7.11, zrc.rml 4.16 and reportlab 3.6.1. I've attached a sample RML file for reproducing the error. 

[Test File.zip](https://github.com/zopefoundation/z3c.rml/files/7296268/Test.File.zip)

**Comment by jamadden** [comment]
In the example error you supplied, you seem to have mis-nested tags; the `</title>` tag appears to be closing the `<para>` opening tag. I can imagine that would cause this error.

However, the example in the .zip file is fully valid XML and doesn't contain this type of error. Are you certain the file you uploaded is actually the file used in the example?

The test file is a very short .rml file, I'll include it below for reference (note that the actual file used DOS line endings, which won't show up here):
```xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no" ?>

<!DOCTYPE document SYSTEM "rml.dtd">

<document filename="Test File.pdf">
<template showBoundary="0">
        <pageTemplate id="main">
            <frame id="first" x1="100" y1="400" width="150" height="200"/>
            <frame id="second" x1="300" y1="400" width="150" height="200"/>
	</pageTemplate>
</template>

<stylesheet>
</stylesheet>

 <story>
 <title>Hello World!</title>
 <para>Foobar</para>
 </story>
</document>
```

**Comment by jcharlto** [comment]
Thanks for the quick reply.

The example in the .zip file is the correct one. I had the same reaction
when I saw the error message. I thought the error handling was wrapping a
<para></para> around the problem text.

The referenced XML file generates an error for me when I include the
<para>Foobar</para> line. If I remove that line, there are no errors. If I
remove the <para> tags, there are no errors.

Thanks,
Jeff

**Comment by jcharlto** [comment]
For what it's worth, I believe the problem may be limited to Windows 10 PCs
(I've duplicated the error on two separate Win10 PCs). However, I was able
to turn my RML file into a PDF on a MacOS High Sierra machine.

**Comment by regebro** [comment]
Is this still a problem on Windows with the latest versions? Because then I might try to look into it, because that's weird.

**Comment by jcharlto** [comment]
It is not an issue anymore. It seemed to be an issue with a particular
Windows patch or configuration. At the time, I was able to get my code
working in a different location. And, now, the original location works as
well, after further Windows updates.

I apologize for not providing all the details on my Windows configuration.
In retrospect, that would be handy to have.

Regards,
Jeff

**Comment by regebro** [comment]
No worries! Thanks!
