### ISSUE TITLE
svg2rlg seems not to be compatible with Python3

### ISSUE THREAD

**Issue by AlbertoMarnetto-Work** [zopefoundation/z3c.rml#98]
I get an error using svg2rlg, which seems to be associated with a Python 2-3 incompatibility. The function `handleText` attempts to use `len` and subscripts on a map returned from `parsePos`, which is allowed in Python 2 but not in 3. 

### What I did:

I tried to use `rml2pdf.parseString` on a RML file containing a SVG image

```
<imageAndFlowables imageName="{{ image_path('bad.svg') }}"  imageWidth="428" imageHeight="538"  imageSide="left">
</imageAndFlowables>
```

### What I expect to happen:

The SVG should have been embedded in the PDF document

### What actually happened:

The function raised exception, with the following traceback

```
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/rml2pdf.py", line 41, in parseString
    doc.process(output)
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/document.py", line 736, in process
    self.processSubDirectives(select=('template', 'story'))
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/directive.py", line 121, in processSubDirectives
    directive.process()
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/template.py", line 46, in process
    self.parent.flowables = super().process()
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/flowable.py", line 1633, in process
    self.processSubDirectives()
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/directive.py", line 121, in processSubDirectives
    directive.process()
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/flowable.py", line 1058, in process
    args = dict(self.getAttributeValues(
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/directive.py", line 71, in getAttributeValues
    value = attr.bind(self).get()
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/attr.py", line 111, in get
    return self.fromUnicode(value)
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/attr.py", line 477, in fromUnicode
    return self._load_svg(value)
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/attr.py", line 512, in _load_svg
    svg = Renderer(value).render(svg)
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/svg2rlg.py", line 811, in render
    self.render(child, self.mainGroup)
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/svg2rlg.py", line 856, in render
    self.render(child, group)
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/svg2rlg.py", line 1070, in render
    handleText(node, subnode, subnode.text.strip())
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/svg2rlg.py", line 1031, in handleText
    if sum(map(len, (xs,ys,dxs,dys))) == 4:
TypeError: object of type 'map' has no len()
```

### What version of Python and Zope/Addons I am using:

* Linux (Debian 11)
* Python 3.9.2
* z3c.rml 4.2.0 (version 3.10.0 also fails)

**Comment by AlbertoMarnetto-Work** [comment]
For convenience, here is a (very simple) svg file causing the error.

![bad](https://user-images.githubusercontent.com/58592261/184331244-5cacdc5b-ad2f-4f7f-8414-9476012593fd.svg)

**Comment by icemac** [comment]
@AlbertoMarnetto-Work Could you please try the changes in #99, if they fix this issue?

**Comment by AlbertoMarnetto-Work** [comment]
Thanks for the feedback. I applied the change, I get now the error “Unknown token at position xx“ (tried with different svg files, but only the error position changes)

My understanding is that the functions `getPos` and `handleText` need some adaptation to the new type returned by `parsePos`. But I do not know the code and may be in error.

Full traceback:

```
Traceback (most recent call last):
[...]
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/rml2pdf.py", line 41, in parseString
    doc.process(output)
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/document.py", line 736, in process
    self.processSubDirectives(select=('template', 'story'))
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/directive.py", line 121, in processSubDirectives
    directive.process()
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/template.py", line 46, in process
    self.parent.flowables = super().process()
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/flowable.py", line 1633, in process
    self.processSubDirectives()
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/directive.py", line 121, in processSubDirectives
    directive.process()
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/flowable.py", line 1058, in process
    args = dict(self.getAttributeValues(
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/directive.py", line 71, in getAttributeValues
    value = attr.bind(self).get()
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/attr.py", line 111, in get
    return self.fromUnicode(value)
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/attr.py", line 477, in fromUnicode
    return self._load_svg(value)
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/attr.py", line 512, in _load_svg
    svg = Renderer(value).render(svg)
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/svg2rlg.py", line 811, in render
    self.render(child, self.mainGroup)
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/svg2rlg.py", line 856, in render
    self.render(child, group)
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/svg2rlg.py", line 1070, in render
    handleText(node, subnode, subnode.text.strip())
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/svg2rlg.py", line 1034, in handleText
    self.applyStyleToShape(shape, subnode)
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/svg2rlg.py", line 1435, in applyStyleToShape
    localstyle = self.nodeStyle(node)
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/svg2rlg.py", line 1418, in nodeStyle
    localstyle = parseStyle.parse(node.get('style'))
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/svg2rlg.py", line 430, in parse
    token, value = next()
  File "/tmp/pyenv1/lib/python3.9/site-packages/z3c/rml/svg2rlg.py", line 76, in lex
    raise SVGError('Unknown token at position %d' %  position)
z3c.rml.svg2rlg.SVGError: Unknown token at position 87
```

**Comment by icemac** [comment]
@AlbertoMarnetto-Work I do not know this package at all, so I closed my PR as it does not seem to be enough to solve the issue.

**Comment by AlbertoMarnetto-Work** [comment]
OK, thanks anyway for the attempt!

**Comment by rapto** [comment]
I got away by using svglib.svg2rlg (https://github.com/deeplook/svglib)

**Comment by regebro** [comment]
We switched to using svglib as well, let's hope that works out.
